AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chat API for pointfree.space

Parameters:
  AllowedOrigin:
    Type: String
    Default: 'https://pointfree.space'
    Description: CORS allowed origin.

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 15
    MemorySize: 128

Resources:

  ChatApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - !Ref AllowedOrigin
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
        MaxAge: 300

  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      CodeUri: .
      Environment:
        Variables:
          MESSAGES_TABLE:       !Ref MessagesTable
          RATE_TABLE:           !Ref RateLimitsTable
          RATE_LIMIT:           '15'
          ALLOWED_ORIGIN:       !Ref AllowedOrigin
          VOICE_TABLE:          !Ref VoiceRoomTable
          TURN_EC2_INSTANCE_ID: 'i-0REPLACE'   # set to '' to disable
          TURN_SECRET:          ''              # set manually after deploy (or use SSM)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RateLimitsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref VoiceRoomTable
        - Statement:
            - Effect: Allow
              Action:
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:DescribeInstances
              Resource: '*'
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatApi
            Path:  /messages
            Method: ANY
        VoiceApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatApi
            Path:  /voice/{proxy+}
            Method: ANY

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-messages
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: room
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: room
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  RateLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-rate-limits
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  VoiceRoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-room
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  TurnIdleStopFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.turnIdleStopHandler
      CodeUri: .
      Environment:
        Variables:
          VOICE_TABLE:          !Ref VoiceRoomTable
          TURN_EC2_INSTANCE_ID: 'i-0REPLACE'   # set to '' to disable
          TURN_SECRET:          ''
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VoiceRoomTable
        - Statement:
            - Effect: Allow
              Action:
                - ec2:StopInstances
                - ec2:DescribeInstances
              Resource: '*'
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

Outputs:
  ApiUrl:
    Value: !Sub 'https://${ChatApi}.execute-api.${AWS::Region}.amazonaws.com'
    Description: >
      Paste this URL into chat.html as window.CHAT_API_BASE after deployment.
      Deploy with: sam build && sam deploy --guided --stack-name personal-site-chat --region us-west-1
